{
    "name": "CartonCloud Connector",
    "author": "Dan Tran",
    "category": "Inventory/Delivery",
    "version": "17.0.1.0.0",
    "depends": [
        "base",
        "sale_management",
        "account",
        "stock",
        "mail",
        "purchase",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/cartoncloud_cron_data.xml",
        "data/cartoncloud_mail_templates.xml",
        "views/cartoncloud_tenant_views.xml",
        "views/sale_order_view.xml",
        "views/stock_picking_view.xml",
        "views/purchase_order_view.xml",
        "views/raw_view.xml",
        "views/raw_line_views.xml",
        "wizards/stock_discrepancy_adjustment_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "license": "OPL-1",
}
